// <auto-generated />
using System;
using FinTech.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FinTech.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FinTech.API.Models.Loan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<decimal>("InterestRate")
                        .HasColumnType("decimal(5,4)");

                    b.Property<string>("LoanType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal?>("MonthlyPayment")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Pending");

                    b.Property<int>("Term")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Loans", null, t =>
                        {
                            t.HasCheckConstraint("CK_Loan_Amount", "\"Amount\" >= 500 AND \"Amount\" <= 50000");

                            t.HasCheckConstraint("CK_Loan_InterestRate", "\"InterestRate\" >= 0.18 AND \"InterestRate\" <= 0.35");

                            t.HasCheckConstraint("CK_Loan_Term", "\"Term\" >= 6 AND \"Term\" <= 60");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("c3d4e5f6-a7b8-9012-cdef-123456789012"),
                            Amount = 5000.00m,
                            CreatedAt = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            InterestRate = 0.24m,
                            LoanType = "Fixed",
                            MonthlyPayment = 467.26m,
                            Status = "Active",
                            Term = 12,
                            UserId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890")
                        });
                });

            modelBuilder.Entity("FinTech.API.Models.PaymentSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Interest")
                        .HasColumnType("decimal(12,2)");

                    b.Property<Guid>("LoanId")
                        .HasColumnType("uuid");

                    b.Property<int>("PaymentNumber")
                        .HasColumnType("integer");

                    b.Property<decimal>("Principal")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("RemainingBalance")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Pending");

                    b.Property<decimal>("TotalPayment")
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("LoanId");

                    b.HasIndex("LoanId", "PaymentNumber")
                        .IsUnique();

                    b.ToTable("PaymentSchedules", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("d4e5f6a7-b8c9-0123-def4-567890123456"),
                            DueDate = new DateTime(2025, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Interest = 90.43m,
                            LoanId = new Guid("c3d4e5f6-a7b8-9012-cdef-123456789012"),
                            PaymentNumber = 1,
                            Principal = 376.83m,
                            RemainingBalance = 4623.17m,
                            Status = "Paid",
                            TotalPayment = 467.26m
                        },
                        new
                        {
                            Id = new Guid("e5f6a7b8-c9d0-1234-ef56-789012345678"),
                            DueDate = new DateTime(2025, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Interest = 83.61m,
                            LoanId = new Guid("c3d4e5f6-a7b8-9012-cdef-123456789012"),
                            PaymentNumber = 2,
                            Principal = 383.65m,
                            RemainingBalance = 4239.52m,
                            Status = "Paid",
                            TotalPayment = 467.26m
                        },
                        new
                        {
                            Id = new Guid("f6a7b8c9-d0e1-2345-f678-901234567890"),
                            DueDate = new DateTime(2025, 4, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Interest = 76.67m,
                            LoanId = new Guid("c3d4e5f6-a7b8-9012-cdef-123456789012"),
                            PaymentNumber = 3,
                            Principal = 390.59m,
                            RemainingBalance = 3848.93m,
                            Status = "Pending",
                            TotalPayment = 467.26m
                        },
                        new
                        {
                            Id = new Guid("a7b8c9d0-e1f2-3456-7890-123456789abc"),
                            DueDate = new DateTime(2025, 5, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Interest = 69.61m,
                            LoanId = new Guid("c3d4e5f6-a7b8-9012-cdef-123456789012"),
                            PaymentNumber = 4,
                            Principal = 397.65m,
                            RemainingBalance = 3451.28m,
                            Status = "Pending",
                            TotalPayment = 467.26m
                        },
                        new
                        {
                            Id = new Guid("b8c9d0e1-f2a3-4567-8901-234567890abc"),
                            DueDate = new DateTime(2025, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Interest = 62.41m,
                            LoanId = new Guid("c3d4e5f6-a7b8-9012-cdef-123456789012"),
                            PaymentNumber = 5,
                            Principal = 404.85m,
                            RemainingBalance = 3046.43m,
                            Status = "Pending",
                            TotalPayment = 467.26m
                        },
                        new
                        {
                            Id = new Guid("c9d0e1f2-a3b4-5678-9012-345678901abc"),
                            DueDate = new DateTime(2025, 7, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Interest = 55.09m,
                            LoanId = new Guid("c3d4e5f6-a7b8-9012-cdef-123456789012"),
                            PaymentNumber = 6,
                            Principal = 412.17m,
                            RemainingBalance = 2634.26m,
                            Status = "Pending",
                            TotalPayment = 467.26m
                        },
                        new
                        {
                            Id = new Guid("d0e1f2a3-b4c5-6789-0123-45678901abcd"),
                            DueDate = new DateTime(2025, 8, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Interest = 47.63m,
                            LoanId = new Guid("c3d4e5f6-a7b8-9012-cdef-123456789012"),
                            PaymentNumber = 7,
                            Principal = 419.63m,
                            RemainingBalance = 2214.63m,
                            Status = "Pending",
                            TotalPayment = 467.26m
                        },
                        new
                        {
                            Id = new Guid("e1f2a3b4-c5d6-7890-1234-5678901abcde"),
                            DueDate = new DateTime(2025, 9, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Interest = 40.04m,
                            LoanId = new Guid("c3d4e5f6-a7b8-9012-cdef-123456789012"),
                            PaymentNumber = 8,
                            Principal = 427.22m,
                            RemainingBalance = 1787.41m,
                            Status = "Pending",
                            TotalPayment = 467.26m
                        },
                        new
                        {
                            Id = new Guid("f2a3b4c5-d6e7-8901-2345-678901abcdef"),
                            DueDate = new DateTime(2025, 10, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Interest = 32.31m,
                            LoanId = new Guid("c3d4e5f6-a7b8-9012-cdef-123456789012"),
                            PaymentNumber = 9,
                            Principal = 434.95m,
                            RemainingBalance = 1352.46m,
                            Status = "Pending",
                            TotalPayment = 467.26m
                        },
                        new
                        {
                            Id = new Guid("a3b4c5d6-e7f8-9012-3456-789012345678"),
                            DueDate = new DateTime(2025, 11, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Interest = 24.44m,
                            LoanId = new Guid("c3d4e5f6-a7b8-9012-cdef-123456789012"),
                            PaymentNumber = 10,
                            Principal = 442.82m,
                            RemainingBalance = 909.64m,
                            Status = "Pending",
                            TotalPayment = 467.26m
                        },
                        new
                        {
                            Id = new Guid("b4c5d6e7-f8a9-0123-4567-890123456789"),
                            DueDate = new DateTime(2025, 12, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Interest = 16.43m,
                            LoanId = new Guid("c3d4e5f6-a7b8-9012-cdef-123456789012"),
                            PaymentNumber = 11,
                            Principal = 450.83m,
                            RemainingBalance = 458.81m,
                            Status = "Pending",
                            TotalPayment = 467.26m
                        },
                        new
                        {
                            Id = new Guid("c5d6e7f8-a9b0-1234-5678-901234567890"),
                            DueDate = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Interest = 8.30m,
                            LoanId = new Guid("c3d4e5f6-a7b8-9012-cdef-123456789012"),
                            PaymentNumber = 12,
                            Principal = 458.81m,
                            RemainingBalance = 0.00m,
                            Status = "Pending",
                            TotalPayment = 467.26m
                        });
                });

            modelBuilder.Entity("FinTech.API.Models.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("LoanId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Pending");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("LoanId");

                    b.HasIndex("Status");

                    b.HasIndex("Type");

                    b.HasIndex("UserId");

                    b.ToTable("Transactions", (string)null);
                });

            modelBuilder.Entity("FinTech.API.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<decimal>("MonthlyIncome")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "juan@email.com",
                            MonthlyIncome = 5000.00m,
                            Name = "Juan Pérez",
                            PasswordHash = "1234"
                        },
                        new
                        {
                            Id = new Guid("b2c3d4e5-f6a7-8901-bcde-f12345678901"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "maria@email.com",
                            MonthlyIncome = 8000.00m,
                            Name = "María García",
                            PasswordHash = "1234"
                        });
                });

            modelBuilder.Entity("FinTech.API.Models.Loan", b =>
                {
                    b.HasOne("FinTech.API.Models.User", "User")
                        .WithMany("Loans")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FinTech.API.Models.PaymentSchedule", b =>
                {
                    b.HasOne("FinTech.API.Models.Loan", "Loan")
                        .WithMany("PaymentSchedules")
                        .HasForeignKey("LoanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Loan");
                });

            modelBuilder.Entity("FinTech.API.Models.Transaction", b =>
                {
                    b.HasOne("FinTech.API.Models.Loan", "Loan")
                        .WithMany()
                        .HasForeignKey("LoanId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FinTech.API.Models.User", "User")
                        .WithMany("Transactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Loan");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FinTech.API.Models.Loan", b =>
                {
                    b.Navigation("PaymentSchedules");
                });

            modelBuilder.Entity("FinTech.API.Models.User", b =>
                {
                    b.Navigation("Loans");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
